"""Create alarm history and import audit schema."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment")),
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_read", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("accepted", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("rejected", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("duplicates", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("accepted_with_warnings", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "status != 'COMPLETED' OR (records_read = accepted + rejected + duplicates "
            "AND finished_at IS NOT NULL)",
            name=op.f("ck_imports_completed_counts"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')",
            name=op.f("ck_imports_status"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at", name=op.f("ck_imports_time_order")
        ),
        sa.CheckConstraint(
            "records_read >= 0 AND accepted >= 0 AND rejected >= 0 AND duplicates >= 0 "
            "AND accepted_with_warnings >= 0 AND accepted_with_warnings <= accepted",
            name=op.f("ck_imports_counters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
    )
    op.create_index("ix_imports_started_at", "imports", ["started_at"], unique=False)
    op.create_table(
        "rejected_records",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("record_number", sa.BigInteger(), nullable=False),
        sa.Column("original_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "CASE WHEN jsonb_typeof(errors) = 'array' "
            "THEN jsonb_array_length(errors) > 0 ELSE false END",
            name=op.f("ck_rejected_records_errors_nonempty"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(original_data) = 'object'",
            name=op.f("ck_rejected_records_original_data_object"),
        ),
        sa.CheckConstraint("record_number > 0", name=op.f("ck_rejected_records_record_number")),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
            name=op.f("fk_rejected_records_import_id_imports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rejected_records")),
        sa.UniqueConstraint("import_id", "record_number", name="uq_rejected_records_import_record"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("equipment_id", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_tags_equipment_id_equipment"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    op.create_index("ix_tags_equipment_id", "tags", ["equipment_id"], unique=False)
    op.create_table(
        "alarms",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=12), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tag_id", sa.String(length=64), nullable=False),
        sa.Column("alarm_code", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("event_id ~ '^EVT-[0-9]{8}$'", name=op.f("ck_alarms_event_id_format")),
        sa.CheckConstraint(
            "jsonb_typeof(warnings) = 'array'", name=op.f("ck_alarms_warnings_array")
        ),
        sa.CheckConstraint(
            "severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f("ck_alarms_severity")
        ),
        sa.CheckConstraint(
            "value IS NULL OR (value >= 0 AND value != 'NaN'::numeric)",
            name=op.f("ck_alarms_value"),
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
            name=op.f("fk_alarms_import_id_imports"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_alarms_tag_id_tags"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alarms")),
        sa.UniqueConstraint("source_system", "event_id", name="uq_alarms_source_event"),
    )
    op.create_index("ix_alarms_import_id", "alarms", ["import_id"], unique=False)
    op.create_index("ix_alarms_occurred_at_id", "alarms", ["occurred_at", "id"], unique=False)
    op.create_index(
        "ix_alarms_severity_occurred_at_id",
        "alarms",
        ["severity", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_alarms_tag_occurred_at_id", "alarms", ["tag_id", "occurred_at", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alarms")
    op.drop_table("tags")
    op.drop_table("rejected_records")
    op.drop_table("imports")
    op.drop_table("equipment")
    # ### end Alembic commands ###
